jobs:
  publish-magic:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - run: cd packages/magic && echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
      - run: cd packages/magic && npm publish --access public

workflows:
  magic:
    jobs:
      - publish-magic:
          filters:
            branches:
              only:
                - main
